# Generated by Django 2.2.1 on 2019-08-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgage', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
