# Generated by Django 3.0.3 on 2020-05-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_querybox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querybox',
            name='query',
            field=models.CharField(max_length=10000),
        ),
    ]
