# Generated by Django 3.0.7 on 2020-07-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20200505_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querybox',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
